language: php
php:
 - 5.5
 - 5.4
before_install:
 - sudo apt-get update
install:
 - sudo apt-get install build-essential
 - sudo apt-get install libbz2-dev
 - sudo apt-get install zlib1g-dev
 - sudo apt-get install libtar-dev
 - sudo apt-get install php-pear
 - sudo apt-get install php5-dev
 - sudo apt-get install make
before_script:
 - echo "extension = phptar.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - phpize
 - ./configure
 - make
 - make install
script:
 - php tests/test-list.php 
 - php tests/test-list.php
