language: php
php:
 - 5.5
 - 5.4
before_script:
 - echo "extension = phptar.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - phpize
 - ./configure
 - make
 - make install
script:
 - php tests/test-list.php 
 - php tests/test-list.php
